### PR TITLE
Solving issue #33, refreshing the README and adapt to FIRST commits

### LINKED ISSUE #33: Macrovector=1 does not always mean "Medium"
I think the data structure in
https://github.com/RedHatProductSecurity/cvss-v4-calculator/blob/5d7a90c66be1f0c1432f8c279e12e856943b7efb/cvss_details.js#L13-L18

is incorrect in its assumption that a macrovector value of 1 always means "Medium".

Macrovectors 1, 3, 4, and 5 can take on 3 values `(0, 1, 2)` so it makes sense that they would have "High, Medium, Low" mapped onto these.

However, Macrovectors 2 and 6 only have 2 values `(0,1)`, which means the data structure referenced above will translate that in the UI to "High, Medium". This begs the question "What about Low?"

Screenshot 2023-10-05 at 9 22 22 AM

I would expect the above to be Low, _Low_, Low, Low, High, _Low_ instead of Low, _Medium_, Low, Low, High, _Medium_.

It seems like the translation for Macrovectors 2 and 6 needs to use a different lookup table. Perhaps something like:

```js
cvssMacroVectorValues2 = {
  "0": "High",
  "1": "Low",
  "2": "None",
}
```

### PR DESCRIPTION
**Pull request by n3rada**
Now than we have a class-based approach and because I am now quite familiar with the code, I can propose this modification in order to close #33:
```
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:P/VC:L/VI:H/VA:L/SC:L/SI:L/SA:N/MVC:L/MVI:L
```
image

### CODE REVIEW

**Comment by n3rada** [comment]
That way, after this merge, we'll be in complete harmony with [FIRST](https://github.com/RedHatProductSecurity/cvss-v4-calculator/compare/main...FIRSTdotorg:cvss-v4-calculator:main), and they'll be able to synchronize their projects and rely on RedHat's quality.

**Comment by pandatix** [comment]
Commit message "Adapting to FISRT commits" has a typo, should be FIRST :)

**Comment by n3rada** [comment]
Typo fixed!

File: cvss40.js [hunk 1]
```diff
@@ -306,20 +307,37 @@ class Vector {
...
+    
+        // Lookup table for macrovectors with two possible values
+        const macroVectorValuesTwoOptions = {
+            "0": "High",
+            "1": "Low"
+        };
+    
+        // Define which macrovectors have three values and which have two
+        const threeValueMacrovectors = [0, 2, 3, 4]; // Indices for macrovectors 1, 3, 4, 5 (0-based index)
+        const twoValueMacrovectors = [1, 5]; // Indices for macrovectors 2 and 6 (0-based index)
```
Comment (superbuggy) [inline cvss40.js]: It would be better to obtain these indexes using `.indexOf`/`.findIndex` rather than using magic numbers. Better yet, the code may be further simplified by using the keys of `macroVectorDetails` with the iterator variable `description` to decide on how many options to present--`.includes` would work well for that implementation.

**Review by superbuggy — CHANGES_REQUESTED** [review]

File: cvss40.js (hunk 1 above)
Comment (n3rada) [reply cvss40.js]: Very good point. I've modified it, trying to think a little more modular than my original proposal. Does that work for you @superbuggy?

Comment (superbuggy) [reply cvss40.js]: The change I was requesting would've been along these lines...
```js
const macroVectorDetails = {
            "Exploitability": 0,
            "Complexity": 1,
            "Vulnerable system": 2,
            "Subsequent system": 3,
            "Exploitation": 4,
            "Security requirements": 5
        };
    
        // Lookup table for macrovectors with three possible values
        const macroVectorValuesThreeOptions = [ "High", "Medium", "Low" ];
    
        // Lookup table for macrovectors with two possible values
        const macroVectorValuesTwoOptions = [ "High", "Low" ]
    
        // Define which macrovectors have two values
        const twoValueMacroVectors = ["Complexity", "Security requirements"]; 
    
        // Construct the detailed breakdown
        return Object.fromEntries(
            Object.entries(macroVectorDetails).map(([description, index]) => {
                const currentValue = macroVector[index]; // This would maybe have to change?
                // Use the appropriate lookup table based on the macrovector
                const macroVectorValueOptions = twoValueMacroVectors.includes(description)
                    ? macroVectorValuesThreeOptions
                    : macroVectorValuesTwoOptions;
                return [
                    description,
                    macroVectorValueOptions[currentValue] // This would maybe have to change?
                ];
            })
        );
```

**Review by superbuggy — CHANGES_REQUESTED** [review]
The code could be simplified and less dependent on hard-coded values or magic numbers.

File: cvss40.js (hunk 1 above)
Comment (superbuggy) [reply cvss40.js]: I'm not sure there's a reason for `macroVectorDetails`  to be a an object, it seems it could just be an array. Maybe something like...

```js
const macroVectorDetails = [
            "Exploitability",
            "Complexity",
            "Vulnerable system",
            "Subsequent system",
            "Exploitation",
            "Security requirements",
        ]
    
        // Lookup table for macrovectors with three possible values
        const threeSeverities = [ "High", "Medium", "Low" ];
    
        // Lookup table for macrovectors with two possible values
        const twoSeverities = [ "High", "Low" ]
    
        // Define which macrovectors have two values
        const macroVectorsWithTwoSeverities = ["Complexity", "Security requirements"]; 
    
        // Construct the detailed breakdown
        return Object.fromEntries(
            macroVectorDetails.map((description, index) => {
                // Use the appropriate lookup table based on the macrovector
                const macroVectorValueOptions = macroVectorsWithTwoSeverities.includes(description)
                    ? threeSeverities
                    : twoSeverities;
                const indexOfOption = macroVector[index];
                return [ description, macroVectorValueOptions[indexOfOption] ];
            })
        );
```

This is probably a little easier to reason about (if it does work correctly).

Comment (n3rada) [reply cvss40.js]: But, this proposal is clearly quite similar to my first code isn't?

Comment (n3rada) [reply cvss40.js]: With this kind of code, the code still has some dependencies on hard-coded values (magic numbers) due to the reliance on fixed severity levels for macrovectors and their descriptions.

These arrays are essentially magic numbers because they represent fixed, non-configurable severity levels without being driven dynamically by data or configuration.

But what is the real problem behind that?

**Comment by n3rada** [comment]
In my opinion, the `severityBreakdown` method is the only place where these values (like the severity levels or macrovector descriptions) are used, then you don't really need to over-engineer the solution. In that case, having some level of hard-coding within the function seem really acceptable.

I am a little out of other ideas for this method. It works, it is great. Let's merge! 😇

**Comment by n3rada** [comment]
Thank you, @skontar. I’m quite disappointed that FIRST doesn’t allow pull requests to their repository for merging upstream. It feels somewhat unprofessional.

**Comment by skontar** [comment]
@n3rada no worries, this is the master development repository. They fork it from time to time to deploy on their site. If some updates were not ported back, it is likely oversight, not intent.

**Comment by skontar** [comment]
We are upstream, BTW.

**Comment by superbuggy** [comment]
> In my opinion, the `severityBreakdown` method is the only place where these values (like the severity levels or macrovector descriptions) are used, then you don't really need to over-engineer the solution. In that case, having some level of hard-coding within the function seem really acceptable.
> 
> I am a little out of other ideas for this method. It works, it is great. Let's merge! 😇

With our implementation, some level of hardcoding is inevitable. With the changes you made, it minimizes the amount of hard-coded values, which is desirable. Thank you again!

**Comment by n3rada** [comment]
So, will any changes made here eventually be reflected on the FIRST website? I know that penetration testers relies on your site in reports. It seems more legit to the community.

**Comment by skontar** [comment]
@n3rada yes, eventually, it should be reflected there.
